services:
  app:
    build:
      context: .
    container_name: nestjs-prisma-blog-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${PORT:-3000}:3000'
    command: sh -c "npx prisma db push && node dist/main"
    networks:
      - infra_default

networks:
  infra_default:
    external: true
